# default
[default_session]
preview_command = "exa --all --git --icons --color=always {}"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "exa --all --git --icons --color=always"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "vim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"
